export const ADD_CONTENT = "ADD_CONTENT"
export const GET_CONTENT = "GET_CONTENT"
export const UPDATE_CONTENT = "UPDATE_CONTENT"
export const DELETE_CONTENT = "DELETE_CONTENT"
export const ADD_TAGS = "ADD_TAGS"
export const GET_TAGS = "GET_TAGS"
